### ISSUE TITLE
没有使用成功，麻烦看看错误原因

### ISSUE THREAD

**Issue by richie-angel** [HelloZJW/mpvue-page-factory#1]
import pageFactory from 'mpvue-page-factory'
import App from './index'

Page(pageFactory(App))

请问你这里的App导入的是什么？
我这边导入Vue

> Sun Sep 09 2018 09:41:07 GMT+0800 (CST) Page 注册错误
VM6278:1 Please do not register multiple Pages in undefined.js
console.error @ VM6278:1
t.error @ WAService.js:18
t.pageHolder @ WAService.js:17
Page @ vendor.js:6009
_ @ App.vue:55
__webpack_require__ @ bootstrap 3ed17eb551afb1f05149:54
webpackJsonpCallback @ bootstrap 3ed17eb551afb1f05149:25
(anonymous) @ app.js:3
require @ WAService.js:18
(anonymous) @ WAService.js:18
(anonymous) @ app.js? [sm]:4
require @ WAService.js:18
(anonymous) @ VM6363:1
scriptLoaded @ appservice?t=1536457264818:18636
VM6278:1 thirdScriptError 
 sdk uncaught third Error 
 APP-SERVICE-Engine:Please do not register multiple Pages in undefined.js 
 Error: APP-SERVICE-Engine:Please do not register multiple Pages in undefined.js

**Comment by HelloZJW** [comment]
这一段代码要替换原来的main.js，App是.vue的页面

**Comment by HelloZJW** [comment]
重复注册页面，你应该把原来的app.$mount()去掉

**Comment by richie-angel** [comment]
`import Vue from 'vue'
import App from '@/App'
import store from '@/store'
import pageFactory from 'mpvue-page-factory'
const app = new Vue(App)
Page(pageFactory(app))`

你看我这样对吗

**Comment by HelloZJW** [comment]
针对程序启动的main.js保持和原来的一致，使用var app = new Vue(App); app.$mount();

我这个库只针对页面级别的main.js入口。 比如你的store是某个具体的页面的话，直接在页面入口
import store from '@/store'
import pageFactory from 'mpvue-page-factory'
Page(pageFactory(store))

**Comment by HelloZJW** [comment]
pages的代码看看

**Comment by richie-angel** [comment]
> module.exports = [
  {
    path: '/pages/goods/index',
    config: {
      navigationBarTitleText: 'xx的小店',
      enablePullDownRefresh: true
    }
  },
  {
    path: '/pages/goods/store',
    config: {
      navigationBarTitleText: '店铺首页',
      enablePullDownRefresh: true
    }
  },
  {
    path: '/pages/goods/detail', 
    config: {
      navigationBarTitleText: '商品详情'
    }
  },
  {
    path: '/pages/goods/hotList',
    config: {
      navigationBarTitleText: '热门商品',
      enablePullDownRefresh: true
    }
  },

**Comment by HelloZJW** [comment]
我知道了.这个库和我那个冲突了。我现在在外面，回去看一下

**Comment by richie-angel** [comment]
好的，感谢了，你这个包解决的问题，我找了很久的解决方案都没有解决

**Comment by HelloZJW** [comment]
我自己也深受困扰..把几乎源码都撸了一遍。才找到方法

**Comment by HelloZJW** [comment]
@richie-angel 你把mpvue-entry改成我的fork，修改内容的话你就自己看commit吧~
```
"mpvue-entry": "git+https://github.com/HelloZJW/mpvue-entry.git",
"mpvue-loader": "git+https://github.com/HelloZJW/mpvue-loader.git",
"mpvue-page-factory": "^1.0.0",
```
### 配置方法:
在你的pages.js相同目录下建一个template.js文件，此文件为入口模板；里面内容为:
```
import pageFactory from 'mpvue-page-factory'
import App from '@/App'

Page(pageFactory(App))
```
然后修改build/webpack.base.conf.js 中MpvueEntry.getEntry()方法的入参
```
// const entry = MpvueEntry.getEntry('./src/pages.js')
const entry = MpvueEntry.getEntry({
  pages: './src/pages.js', //可以不填，缺省就是这个
  main: './src/main.js',  //可以不填，缺省就是这个
  template: './src/template.js' //这就是你创建的page入口模板
})
```
然后你会发现node_module/mpvue-entry/dist目录里面js文件内容发生了变化。
![image](https://user-images.githubusercontent.com/8361397/45264454-43671a00-b46f-11e8-8b4f-ecfd534a4755.png)
enjoy，其他工程代码不需要修改

**Comment by richie-angel** [comment]
非常感谢，现在可以使用了，不过有个小问题，在main.js里面获取不到getApp()方法了

**Comment by richie-angel** [comment]
那个getApp无所谓了，我之前不知道可以通过$root去取，不过我发现还是不能解决我的问题，我商品详情页有个loading，当为true的时候会显示全覆盖骨架图，但是安卓端总是会显示下loading为false的状态，再显示这个骨架图

**Comment by HelloZJW** [comment]
@richie-angel 会不会是其他的原因呢，现在我这个方法是每次页面加载的时候都会重新创建一个vue实例挂在小程序的page 上面

**Comment by richie-angel** [comment]
你那边有没有试过安卓端的效果，我现在也很纳闷儿，好像其他数据都已经被清空了，但是就loading这个值会被默认为false，我在data里面定义的是true

**Comment by HelloZJW** [comment]
有loading但是没遇到过你这种问题

**Comment by richie-angel** [comment]
我觉得应该是别的问题了，我刚刚试了下我重新加了个变量，把内容的其他部分用另一个变量控制好像就没有问题了
你如果有空可以看看我现在项目《就爱小店》，小程序应该能搜到，进入商品详情，安卓端能复现我的问题

**Comment by HelloZJW** [comment]
你再看看是不是业务逻辑的问题。

**Comment by richie-angel** [comment]
感觉是渲染的问题，我在同一位置加了另一个变量，分开控制显示就好了

**Comment by HelloZJW** [comment]
对了,你那个build/webpack.base.conf.js 里面的配置需要修改一下。我最新提交的代码，支持外部模板解析，之前的那个判断有点low
const entry = MpvueEntry.getEntry({
  pages: './src/pages.js', //可以不填，缺省就是这个
  main: './src/main.js',  //可以不填，缺省就是这个
  template: './src/template.js',
  templateParser:function(paths){
    let template = fs.readFileSync(paths.template).toString();
    return template;
  }
})

**Comment by HelloZJW** [comment]
对了,你那个build/webpack.base.conf.js 里面的配置需要修改一下。我最新提交的代码，支持外部模板解析，之前的那个判断有点low
```
const fs = require('fs');
const entry = MpvueEntry.getEntry({
  pages: './src/pages.js', //可以不填，缺省就是这个
  main: './src/main.js',  //可以不填，缺省就是这个
  template: './src/template.js',
  templateParser:function(paths){
    let template = fs.readFileSync(paths.template).toString();
    return template;
  }
})
```

**Comment by richie-angel** [comment]
刚刚发现打包的时候有问题
![image](https://user-images.githubusercontent.com/24796096/45273577-ed818900-b4e5-11e8-9c39-3904a0f63c83.png)
