### ISSUE TITLE
 貌似数据快速更新时会出现白屏问题

### ISSUE THREAD

**Issue by zxzhgk** [HelloZJW/mpvue-page-factory#14]
未使用之前：![正常.gif](https://upload-images.jianshu.io/upload_images/3356839-93b390d3533fa87c.gif?imageMogr2/auto-orient/strip)
使用之后：![出错.gif](https://upload-images.jianshu.io/upload_images/3356839-7c654ea46363d858.gif?imageMogr2/auto-orient/strip)

**Comment by zxzhgk** [comment]
项目代码完全一样，只是后面的使用了mpvue-page-factory

**Comment by zxzhgk** [comment]
还有，大神这个库确实解决了同一页面共用一个page的问题，为什么没有向mpvue提交PR，而是单独放出一个库呢

**Comment by zxzhgk** [comment]
使用了props  的子组件偶尔也会出现白屏的问题，不知道是不是也是因为这个原因

**Comment by HelloZJW** [comment]
@zxzhgk 提交了PR 没人合， 不过我没遇到过白屏的问题

**Comment by zxzhgk** [comment]
> @zxzhgk 提交了PR 没人合， 不过我没遇到过白屏的问题
我是给页面绑定一个监听手指滑动的事件，监听了手指滑动，我看了下您的源码，也没看到有diff 数据的地方，等下我再仔看看吧 以下是我的滑动的解构片段
~~~
<!-- 滑动验证 -->
                <div class="verifybox">
                    <div class="slidersBox">
                        <div>{{hint}}</div>
                        <div class='operationBgBox' :class="{succeed:succeedMsg!=''}" :style='{left:-(w+1)+"px",transform:cssAnimation}'>
                            <div>{{ succeedMsg }}</div>
                            <div class='operationBox' @touchmove='moveFun' @touchend='endFun'>
                                <img :src='imgSport' v-show="succeedMsg==''">
                            </div>
                        </div>
                    </div>
                </div>
~~~

**Comment by zxzhgk** [comment]
会不会是最新mpvue https://github.com/Meituan-Dianping/mpvue/pull/1165 更新的这个优化的方法没有没触发导致的

**Comment by zxzhgk** [comment]
问题已解决，发现原因是如果个别页面有类似定时器 或者swiper 在页面onHide 里如果不清除，会在大量持续更新数据时触发定时器导致上一个页面的整个页面数据被setData,着一瞬间的数据之间导致小程序崩溃
