### ISSUE TITLE
请问mpvue2.0.0的版本可以用1.1.x的方法吗？

### ISSUE THREAD

**Issue by mangoooooo** [HelloZJW/mpvue-page-factory#16]
请问mpvue2.0.0的版本可以用1.1.x的方法吗？

**Comment by HelloZJW** [comment]
@mangoooooo 我竟然没注意到2.0.0版本更新了。。我看一下，谢谢提醒！

**Comment by winterfeel** [comment]
同问，mpvue这个bug太久了

**Comment by HelloZJW** [comment]
@winterfeel @mangoooooo 方法都一样，可以看一下我修改的mpvue-loader的代码，其实就加了一个函数，很简单的。

**Comment by mangoooooo** [comment]
@HelloZJW 你好我run dev报错，能帮忙看看是为什么吗？
![image](https://user-images.githubusercontent.com/16449593/53146860-b52bbe00-35e0-11e9-85a8-d6d9c42d7a4f.png)

我已经按照流程加了代码了，并且我没有使用mpvue-entry
![image](https://user-images.githubusercontent.com/16449593/53146891-cb397e80-35e0-11e9-9999-9f925d82487d.png)

**Comment by mangoooooo** [comment]
run dev成功了 我自己fork了最新的mpvue-loader
按照作者的提交记录修改了lib/mp-compiler/parse.js    加了一个函数
