### ISSUE TITLE
打包时出现问题

### ISSUE THREAD

**Issue by richie-angel** [HelloZJW/mpvue-page-factory#2]
![image](https://user-images.githubusercontent.com/24796096/45273853-1ce4c580-b4e7-11e8-97d9-6e8c196e31ca.png)

**Comment by richie-angel** [comment]
`{
        test: /\.js$/,
        include: [resolve('src'), resolve('test'), /mpvue-page-factory/],`

貌似是转的时候出现了问题，我把过滤掉就可以了

**Comment by HelloZJW** [comment]
我这没有重现这个问题诶。我用的公司的项目也试了，打包也没有这个问题。
