### ISSUE TITLE
如果vue模板里面没有script这一个标签，脚本会卡死

### ISSUE THREAD

**Issue by singleparty** [HelloZJW/mpvue-page-factory#3]
首先感谢作者开源，确实能修复mpvue的问题
在使用过程中，使用npm run dev会发现脚本卡死
经过排查，是因为模板里面没有 <script></script> 标签导致的，只要加上就没问题，就算空标签。
这是比较小的兼容问题吧

**Comment by HelloZJW** [comment]
我这边试了下没有发现类似的问题，理论上来说是不会影响脚本编译的

**Comment by HelloZJW** [comment]
试了下确实有这个问题，这个应该是mpvue 本身的问题。

**Comment by HelloZJW** [comment]
@singleparty 这个问题mpvue-loader 1.1.3版本修复了，但是该版本还未正式发布，我的代码他们也没合并，你可以关注一下https://github.com/Meituan-Dianping/mpvue/issues/562
