### ISSUE TITLE
关于Build之后没有app.json等文件

### ISSUE THREAD

**Issue by lamking** [HelloZJW/mpvue-page-factory#4]
使用了 "mpvue-loader": "git+https://github.com/HelloZJW/mpvue-loader.git",  之后
build完就没了app.json文件。。

**Comment by HelloZJW** [comment]
master分支是基于1.1.2版本的，如果你之前用的是老版本，因为目录结构不一样会有问题。2个方法解决:
1. 直接使用我的1.0.x的分支 
```
"mpvue-loader": "git+https://github.com/HelloZJW/mpvue-loader.git#patch1.0.x"
```
2. 参考[升级指南](http://mpvue.com/change-log/2018.7.24/)

**Comment by lamking** [comment]
十分感谢！
