### ISSUE TITLE
通过MpvueEntry导入后,会导致页面跳转触发两次onLoad

### ISSUE THREAD

**Issue by ivanlee93** [HelloZJW/mpvue-page-factory#5]
通过MpvueEntry导入后,会导致页面跳转触发两次onLoad

**Comment by Hansuku** [comment]
+1 我没用 MpvueEntry 一样会触发两次 onLoad

**Comment by Hansuku** [comment]
@HelloZJW 
`"mpvue": "^1.0.11",`
`"mpvue-loader": "^1.1.2",`
版本是这样

**Comment by HelloZJW** [comment]
mpvue-page-factory 版本

**Comment by HelloZJW** [comment]
@Hansuku 
"mpvue-loader": "git+https://github.com/HelloZJW/mpvue-loader.git",
"mpvue-page-factory": "^1.0.1",

**Comment by Hansuku** [comment]
@HelloZJW 貌似可以了 早上不知道是为啥出两次 操作都是一样的...
